
# Site settings
title: aopod's app
owner: aopod
privacy_email: aopodcom+privacy@gmail.com
description: >-
  aopod
baseurl: ""
url: "https://app.aopod.com"
timezone: Asia/Shanghai
encoding: utf-8
sass:
  sass_dir: _sass

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      author: "aopod"
  -
    scope:
      path: "_apps/Shopod"
    values:
      permalink: /Shopod/:basename
  -
    scope:
      path: "_apps/Shopod/privacy"
    values:
      permalink: /Shopod/privacy/:basename/

include:
  - _apps

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
